apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuber557
  namespace: argocd
  finalizers:
    - resources-finalizar.argocd.argoproj.io
spec:
  project: default

  # source of the application manifests
  source: 
    repoURL: git@github.com:kernel87i/argocd.git
    targetRevision: main
    path: k8s/chart
    
    helm:
      valueFiles:
      - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: test

  syncPolicy:
    automated:
      prune: true       
      selfHeal: true # Namespace Auto-creation
    syncOptions:
    - CreateNamespace=true      
