---
apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Chart.Name }}
  labels:
    project: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.containers.containerPort }}
      {{ .Values.service.typePort }}: {{ .Values.service.port}}
  selector:
    app: {{ .Chart.Name }}